---
- name: Converge
  hosts: all
  tasks:
    - name: Configure NGINX
      ansible.builtin.include_role:
        name: ansible-role-nginx-config
      vars:
        nginx_config_debug_output: true

        nginx_config_cleanup: true
        nginx_config_cleanup_paths:
          - directory:
              - /etc/nginx/conf.d
            recurse: false
        nginx_config_cleanup_files:
          - /etc/nginx/conf.d/default.conf

        nginx_config_modules:
          - modules/ngx_http_js_module.so
