---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX Plus is installed
      ansible.builtin.package:
        name: nginx-plus
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX service is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)
